# Generated by Django 4.1.3 on 2022-11-20 14:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название склада')),
                ('fullness', models.IntegerField(verbose_name='Объем груза в наличии')),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Полигон')),
                ('cargo_characteristics', models.JSONField(verbose_name='Качественные характеристики груза')),
            ],
        ),
        migrations.CreateModel(
            name='Tippers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_number', models.CharField(max_length=4, verbose_name='Бортовой номер')),
                ('model', models.CharField(max_length=20, verbose_name='Модель')),
                ('max_load_capacity', models.IntegerField(verbose_name='Максимальная гразоподъемность')),
                ('cargo', models.IntegerField(verbose_name='Груз везет')),
                ('cargo_characteristics', models.JSONField(verbose_name='Качественные характеристики груза')),
            ],
        ),
    ]
